#cloud-config
package_update: true
package_upgrade: true
packages:
- avahi-daemon
- qemu-system-x86
- build-essential
- python3-pip

runcmd:
- mkdir /run/docker-install
- curl -fsSL https://get.docker.com -o /run/docker-install/get-docker.sh
- sh /run/docker-install/get-docker.sh
- mkdir /run/golang-install
- curl -fsSL https://golang.org/dl/go1.17.linux-amd64.tar.gz -o /run/golang-install/go1.17.linux-amd64.tar.gz
- rm -rf /usr/local/go && tar -C /usr/local -xzf /run/golang-install/go1.17.linux-amd64.tar.gz
- echo 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin' | tee /etc/profile.d/go.sh
- pip install diskimage-builder
