# cloud-config
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC61Aao3kZyR1thDTwIvYiHuBafR/429kk99m/FumeuHHVouRie5ARjyOmF2ZqKn5obpEX79LbWJ7GzLVgJ/60HkyUZnuJR9UZssMUnxAKQA97Xw47TtjQApvWYgmYLHD63Vt839vd7JIHLWzwJ/Ou5S7QqH6uWArM/kvdBLDbtYn+pyDSJBj3+pz+2MRUPKnqTLmY0nMfWcmjkj6jXVGNsx5SawU9HRvT9A8l5B5W2c1kk77eHsX5OIM6/HrzskO2Fck0q7C5y54VMeqhDtyqV96HL5qlueAt/BnW1Zj0TN0atrqrpFx341JzsMT/P6OoVdrlGDKKrR1j6RdM4v1VZQXY++khig6wHsN22uYs2AHpKyT+DF0oUbWicpf/mKdBBHUrH3mCkvAtiSO/7Xq9a2mZpqMmayFrgs3L8Il0Yv8aqsZwXRibpIj7cc30VGeLwO0HhiHR4jk8TT6mcaNrgbZ3JFmfeDXhUqAuL/hKeyzrJMlsQoFli8u7EbuwnFQc= ubuntu@primary
package_update: true
package_upgrade: true
write_files:
- content: |
    set tabstop=2
    set shiftwidth=2
    set expandtab
    set textwidth=0
  path: /etc/vim/vimrc.local
  permissions: '0644'
