# cloud-config
package_update: true
packages:
- ansible
package_upgrade: true
write_files:
- content: |
    set tabstop=2
    set shiftwidth=2
    set expandtab
    set textwidth=0
  path: /etc/vim/vimrc.local
  permissions: '0644'
